feat(CROSS-875):Request repo workflows & determine the 1 to be launched
Telefonica/cross-platform-actions pull request #33
Opened 2023-05-10 17:43 UTC by JavierIbanezSoloaga

# CROSS-875 - Request repo workflows and determine the one to be launched

## Description

* Get list of the repository workflows
* Find in the list the one to deploy by checking that the workflow_id provided is the name or the yaml file of one of them.
* workflow_id can now be the id of the workflow to deploy. In this case it will be dispatched without listing the repository workflows.

## Check list

* [ ] Unit tests have been executed locally
* [ ] Build has been executed locally
* [ ] The dist folder has been updated
* [ ] The documentation has been updated

2023-05-11 06:23 UTC, javierbrea requested changes
Please add changes to the CHANGELOG.md file, and very important: Update the docs.

2023-05-11 06:23 UTC, javierbrea commented on deploy-platform/src/lib/workflows/Workflows.ts
> +    if (!foundWorkflow) {
Instead of adding more `if` statements, you can simply return the workflow if it was found. It performs better:
```js
if(foundWorkflow) return workflow
```

Even better, instead of creating such a big function with a lot of `if` statements, you could separate it in smaller methods with a very clear responsibility: `findWorkflowWithPathEqualToLowercaseName`, `findWorkflowWithPathEqualsToLowercaseNameReplacingDashes`, `findWorkflowByName`, etc.. Each method simply returns the result of the find. And here, it would so clear as legible as doing something like:

```js
return findWorkflowWithPathEqualToLowercaseName(worflows, workflowName) ||
           findWorkflowWithPathEqualsToLowercaseNameReplacingDashes(worflows, workflowName) ||
           findWorkflowByName(workflows, workflowName);
```

2023-05-11 06:23 UTC, javierbrea commented on deploy-platform/src/lib/workflows/Workflows.ts
> +      workflow.path.toLowerCase().includes(workflowId.toLowerCase())
Includes? Would it be better to use `endsWith`? Another point is that from now, we would be also supporting file names in upper case, as `DEPLOY-X.yml`, which probably is good, but we should specify it in the docs and CHANGELOG too.

2023-05-11 06:23 UTC, javierbrea commented on deploy-platform/src/lib/workflows/Workflows.ts
> +    return foundWorkflow["id"];
Better use dot notation. And please, enable the eslint rule enforcing it.

2023-05-11 06:23 UTC, javierbrea commented on deploy-platform/src/lib/workflows/Workflows.ts
Please add a `log.info` providing information about the pattern that matched the workflow. Something like: `Using workflow id X because it was defined in config`, or `Using workflow file name y because it matches with environment Y`

2023-05-11 06:23 UTC, javierbrea commented on deploy-platform/test/unit/specs/Deploy.test.ts
> +      });
Repeated block. Please create a helper in support as we do for mocking other libraries, or move it to a common `beforeEach` statement

2023-05-11 06:23 UTC, javierbrea commented on deploy-platform/test/unit/specs/Deploy.test.ts
> +          .spyOn(workflowsLib.Workflows.prototype, "findWorkflowToDispatch")
Mmmm... here you are mocking the implementation of other internal element. It has not necessarily to be bad, but remember: The most your tests are coupled to your internal implementation, the harder are they to maintain, and the harder is to refactor the whole library. Moving this logic to the config module, as I suggested in a previous comment, would also make this test unnecessary, which is in fact very good 😉

2023-05-11 06:23 UTC, javierbrea commented on deploy-platform/test/unit/specs/workflows/Workflows.test.ts
> +    });
Refactor this method in the way I suggested you above, would make this tests very much simpler, and you won't need to mock anything, because you will have methods that will simply receive an array of `workflows`, and a `workflowFileName`. Then, you can pass plain objects to test the functionality of those methods in a very simple and legible way. And don't abuse of using constants for testing them, sometimes it is better to see the content that you are passing to the tested method, than a constant (use constants or methods for getting fixtures only when they are very complex and it would be very repetitive to create them n times for n tests)

2023-05-11 06:23 UTC, javierbrea commented on deploy-platform/dist/src/lib/workflows/Workflows.types.d.ts
> +    findWorkflowToDispatch(workflowId: string): Promise<number>;
Or even better, read my comment below. It should be named simply `workfowFileName`

2023-05-11 06:23 UTC, javierbrea commented on deploy-platform/test/unit/specs/Deploy.test.ts
Here I miss tests checking the functionality from the external layer. I mean, you can mock the response of the `getWorkflows` response, and the input provided, and check which parameter was passed as workflowId to github when dispatching the workflow. A kind of `component tests`.

2023-05-11 06:37 UTC, javierbrea requested changes

2023-05-11 06:37 UTC, javierbrea commented on deploy-platform/dist/src/lib/workflows/Workflows.types.d.ts
> +    findWorkflowToDispatch(workflowId: string): Promise<number>;
Don't be afraid to refactor when needed. If a new requirement makes the name of a variable inconsistent, it is better to change it everywhere according to the new scenario, than accumulating "technical debts" that would produce "WTF?" to future code readers (including you in the future). When we read the code, we ignore the context of the previous states, we only care about the CURRENT state of the code. Have you ever thought "what was this people thinking about when they wrote this code?", well, that code probably was very consistent in the beginning too. What normally makes the code to degrade is the accumulation of changes without stopping to think about the coherence of the whole system after each change, not an initial plan to make it bad 😉  So, let's avoid the [Software entropy](https://en.wikipedia.org/wiki/Software_entropy) by making continuous refactor! 😃

2023-05-11 14:06 UTC, JavierIbanezSoloaga commented on deploy-platform/dist/src/lib/workflows/Workflows.types.d.ts
> +    findWorkflowToDispatch(workflowId: string): Promise<number>;
Done

2023-05-11 14:06 UTC, JavierIbanezSoloaga commented on deploy-platform/src/lib/Deploy.ts
> +  const workflowId = isNaN(Number(config.workflowId))
Done

2023-05-11 14:06 UTC, JavierIbanezSoloaga commented on deploy-platform/src/lib/workflows/Workflows.ts
> +  public async findWorkflowToDispatch(workflowId: string): Promise<number> {
Done

2023-05-11 14:06 UTC, JavierIbanezSoloaga commented on deploy-platform/src/lib/workflows/Workflows.ts
> +    workflowId: string
Done

2023-05-11 14:07 UTC, JavierIbanezSoloaga commented on deploy-platform/src/lib/workflows/Workflows.ts
> +    if (!foundWorkflow) {
Done

2023-05-11 14:07 UTC, JavierIbanezSoloaga commented on deploy-platform/test/unit/specs/Deploy.test.ts
> +      });
Erased

2023-05-11 14:08 UTC, JavierIbanezSoloaga commented on deploy-platform/test/unit/specs/Deploy.test.ts
> +          .spyOn(workflowsLib.Workflows.prototype, "findWorkflowToDispatch")
Erased

2023-05-11 14:09 UTC, JavierIbanezSoloaga commented on deploy-platform/test/unit/specs/workflows/Workflows.test.ts
> +    });
I refactor that function but the ones that i created to find the workflow to deploy are declared private and i have no access to its in this test

2023-05-11 14:09 UTC, JavierIbanezSoloaga commented on deploy-platform/test/unit/specs/Deploy.test.ts
Done

2023-05-11 14:23 UTC, JavierIbanezSoloaga commented on deploy-platform/src/lib/workflows/Workflows.ts
It is already providing information about the calls it does to the github API and its parameters. I do not see necessary more info about what decision is taken according to the inputs provided. Also i do not understand what are you wanting to log very well...

2023-05-11 16:05 UTC, javierbrea commented on deploy-platform/test/unit/specs/workflows/Workflows.test.ts
> +    });
Would it be better then to not declare those methods as private methods of the class? I suppose that you are not accessing to anything related to the class itself, I mean, if methods are receiving everything as arguments, and they do not use `this`, they probably should be declared as functions outside the class.

2023-05-11 16:09 UTC, javierbrea commented on deploy-platform/src/lib/workflows/Workflows.ts
But that logs are only visible in debug mode, am I right? I mean that it would be useful to the user to see some more "human friendly" logs about the important decisions that the library makes, especially when they are related to conventions, such as the workflow file names. This is because, unfortunately, writing docs does not guarantee that they are read, many developers start trying libraries directly, and providing this kind of information would be useful for them to determine how it works, in case the dispatched workflow is not the one than they expected.

2023-05-12 11:12 UTC, JavierIbanezSoloaga commented on deploy-platform/test/unit/specs/workflows/Workflows.test.ts
> +    });
Done

2023-05-12 11:12 UTC, JavierIbanezSoloaga commented on deploy-platform/src/lib/workflows/Workflows.ts
Done

2023-05-12 12:29 UTC, javierbrea requested changes

2023-05-12 12:29 UTC, javierbrea commented on deploy-platform/src/lib/workflows/Workflows.ts
> +    this._logger.info(`Found workflow ${foundWorkflow.name} matching with ${workflowFileName}`);
Should we display the file name instead of the name?
```suggestion
    this._logger.info(`Found workflow with fileName "${foundWorkflow.path.split("/").pop()}" and name "${foundWorkflow.name}" matching with "${workflowFileName}"`);
```

2023-05-12 12:29 UTC, javierbrea commented on deploy-platform/src/lib/workflows/Workflows.types.ts
> +  findWorkflowToDispatch(workflowId: string): Promise<number>;
```suggestion
  findWorkflowToDispatch(workflowName: string): Promise<number>;
```

2023-05-12 12:29 UTC, javierbrea commented on deploy-platform/test/unit/specs/config/Config.test.ts
> +    describe("when ref are provided", () => {
```suggestion
    describe("when ref is provided", () => {
```

2023-05-12 12:29 UTC, javierbrea commented on deploy-platform/test/unit/specs/config/Config.test.ts
> +        expect(config.workflowFileName).toEqual("foo-workflow-id");
```suggestion
        expect(config.workflowFileName).toEqual("foo-workflow-id");
        expect(config.workflowId).toBeUndefined();
```

2023-05-12 12:29 UTC, javierbrea commented on deploy-platform/test/unit/specs/config/Config.test.ts
> +        expect(config2.workflowId).toEqual(1234);
```suggestion
        expect(config2.workflowId).toEqual(1234);
        expect(config2.workflowName).toBeUndefined();
```

2023-05-12 12:54 UTC, javierbrea approved these changes

2023-05-12 12:55 UTC, merged