feat(CROSS-1093): Configurable polling interval
Telefonica/cross-platform-actions pull request #49
Opened 2023-06-05 11:31 UTC by JavierIbanezSoloaga

# CROSS-1093 - Configurable polling interval

## Description

* Add optional input to configure the interval between request to github API
* Increase default request interval

## Check list

* [ ] Unit tests have been executed locally
* [ ] Build has been executed locally
* [ ] The dist folder has been updated
* [ ] The documentation has been updated

2023-06-05 14:07 UTC, rpiccio submitted a review, later dismissed

2023-06-05 15:44 UTC, javierbrea requested changes
Please add a detailed description of the changes to the `unreleased` section of the CHANGELOG.md file (I think that the procedure is detailed in the README.md file)

2023-06-05 15:44 UTC, javierbrea commented on deploy-platform/src/github-action/Action.ts
> +    }
Giving default values and the validation of params should be done in the config module. Here the logic should be kept at minimums, as it currently is.

2023-06-05 15:44 UTC, javierbrea commented on deploy-platform/test/unit/specs/Action.test.ts
> +    it("should set action to error when request interval is not a number", async () => {
The error should be thrown by the config method, not by the action. So, this test description should be also changed.

2023-06-05 16:07 UTC, JavierIbanezSoloaga commented on deploy-platform/test/unit/specs/Action.test.ts
> +    it("should set action to error when request interval is not a number", async () => {
As i mentioned before, IMO its action's duty this logic

2023-06-05 16:19 UTC, javierbrea commented on deploy-platform/src/github-action/Action.ts
> +    }
Ok, but then, create a "config" submodule or a "sanitize inputs" separated function. Avoid also to pass `undefined` in an `else` explicitly. I mean, the call to the `deployAndGetArtifact` method should be present only once here. And there shouldn't be `if` conditionals.

2023-06-05 16:20 UTC, javierbrea commented on deploy-platform/src/github-action/Action.ts
> +    }
And remember to handle errors by throwing, apart of using the core to set failed 😉

2023-06-05 16:43 UTC, JavierIbanezSoloaga commented on deploy-platform/src/github-action/Action.ts
> +    }
Done

2023-06-06 05:57 UTC, javierbrea requested changes
Please don't forget to add changes to the CHANGELOG.md file

2023-06-06 05:57 UTC, javierbrea commented on deploy-platform/src/github-action/Inputs.ts
> +  }
Why are you explicitly setting `requestInterval` to undefined? I suppose that it is because github actions give you a value of empty string when it is not defined. But here it is very strange to see this. So, maybe it would be more understable if you change the comparison to a difference of empty string. Or even better, simply pass the empty string, because I can see in the config that it is compatible with it.

```suggestion
  if (inputs.requestInterval !== "") {
    const requestInterval = parseInt(inputs.requestInterval);
    if (isNaN(requestInterval)) {
      throw new Error("Input request-interval must be a number");
    }
    return { ...inputs, requestInterval };
  }
  return inputs;
```

2023-06-06 07:34 UTC, JavierIbanezSoloaga commented on deploy-platform/src/github-action/Inputs.ts
> +  }
Solved

2023-06-06 08:24 UTC, merged