feat(CROSS-1455): add write secret action
Telefonica/cross-platform-actions pull request #60
Opened 2023-06-20 19:17 UTC by ismtabo

# CROSS-1455 - Create workflow to sync deploy manifest to project repository

## Description

Added `write-secret` Github Action to write secrets to other repositories or environments. This action will be part of the actions require for the synchronization of deploy manifest in the instances repositories with the project repositories/environments.

Added NX tool to ease the management of monorepo projects and tasks.

## Check list

* [x] Unit tests have been executed locally
* [x] Build has been executed locally
* [x] The dist folder has been updated
* [x] The documentation has been updated

2023-06-22 10:42 UTC, rpiccio approved these changes
I think it would be easier to pass repositories as new-line separated values instead of JSON array although it may require a little more parsing from the action side:

repositories: |
  repo1
  repo2

2023-06-22 10:49 UTC, rpiccio commented
It may be also interesting to clarify in the README what happens when an environment has been specified but it not exists in one of the repositories:

 - Will the environment be created?
 - Will the secret be write at repository level?
 - Will be skipped?
 - Will produce an error?

2023-06-22 10:52 UTC, ismtabo commented
> I think it would be easier to pass repositories as new-line separated values instead of JSON array although it may require a little more parsing from the action side:
> 
> repositories: | repo1 repo2

I will take a look to the state of art of actions to check which is the common way to have list inputs (new-line separated, comma separated, JSON...).

2023-06-22 11:33 UTC, javierbrea requested changes

2023-06-22 11:33 UTC, javierbrea commented on nx.json
> +      "dependsOn": ["^build"],
It depends on its own build, am I right?

```suggestion
      "dependsOn": ["build"],
```

2023-06-22 11:33 UTC, javierbrea commented on nx.json
> +      "dependsOn": ["^build"]
It depends on its own build, am I right?
```suggestion
      "dependsOn": ["build"]
```

If you also want that dependencies are also built first, you can add:
```json
"build": {
      "dependsOn": ["^build"],
}
```

2023-06-22 11:33 UTC, javierbrea commented on write-secret/.eslintrc.js
> +  ignorePatterns: ["node_modules", "dist/**/*", "coverage/**/*"],
You could move common config between both TypeScript packages to the root eslintconfig. Eslint takes care of extending them deeply. (Probably, some configuration in the other package currently is  neither really needed, because it may be already defined in the root config)

2023-06-22 11:33 UTC, javierbrea commented on write-secret/README.md
> +Component tests are executed in a real environment, using the GitHub Actions Runner. The action is executed in the workflow, and it dispatches the `deploy-test.yml` workflow in this same repository.
Component tests description should be updated

2023-06-22 11:33 UTC, javierbrea commented on write-secret/package.json
> +}
Missing new line at end of file

2023-06-22 11:33 UTC, javierbrea commented on write-secret/package.json
> +    "@types/jest": "29.5.2",
Move to root dependencies from both packages?

2023-06-22 11:33 UTC, javierbrea commented on write-secret/src/index.ts
> +runDeployAndGetArtifactAction();
```suggestion
writeSecretAndGetArtifactAction();
```

2023-06-22 11:33 UTC, javierbrea commented on write-secret/src/lib/WriteSecret.ts
> +  }
Could be moved to another method, and called here by using `const createdSecrets = await Promise.all(config.repositories.map(getSecret))`?

2023-06-22 11:33 UTC, javierbrea commented on write-secret/src/lib/github/Repository.ts
> +  private async _getPublicKey(): Promise<PublicKeyInterface> {
Should be this cached? I mean, just in case the instance public methods could be called more than once. If that is not the case, it does not matter.

2023-06-22 11:33 UTC, javierbrea commented on write-secret/test/unit/specs/lib/github/Environment.test.ts
> +    const environment = new Environment(NaN, name, { octokit: getOctokit(token) });
Why do you pass `NaN` as environment id?

2023-06-22 11:33 UTC, javierbrea commented on write-secret/test/unit/support/matchers/toHaveEncryptedValue.ts
> +expect.extend({ toHaveEncryptedValue });
❤️

2023-06-22 11:45 UTC, JavierIbanezSoloaga commented on write-secret/README.md
> +__So, you can use this action in the a project's repository to update secrets in a list of repositories or environments. Such as deploy manifest information.__
```suggestion
__So, you can use this action in a project's repository to update secrets in a list of repositories or environments. Such as deploy manifest information.__
```

2023-06-22 11:45 UTC, JavierIbanezSoloaga commented on write-secret/package.json
> +}
Missing empty line at the end of the file

2023-06-22 11:45 UTC, JavierIbanezSoloaga commented on write-secret/README.md
> +__So, you can use this action in the a project's repository to update secrets in a list of repositories or environments. Such as deploy manifest information.__
question: I think this line can lead to misunderstandigs because it seems, at least to me, that you can provide a list of repositories or a list of enviroments and as I see in the code the param list of repositories is always required. So I don't know if the way that should behave this action is like it's described here or it's like it's implemented in the code.

2023-06-22 14:09 UTC, ismtabo commented on write-secret/README.md
> +__So, you can use this action in the a project's repository to update secrets in a list of repositories or environments. Such as deploy manifest information.__
I understand the context can be obtained from the rest of the document. But I'll try to write it better.

2023-06-23 06:20 UTC, ismtabo commented
> I think it would be easier to pass repositories as new-line separated values instead of JSON array although it may require a little more parsing from the action side:
> 
> repositories: | repo1 repo2

After taking a look to others actions, you are right. I will change repositories input to accept a list of values separated by space characters (space, tab, new-line, ...).

2023-06-23 07:36 UTC, rpiccio requested changes

2023-06-23 07:36 UTC, rpiccio commented on write-secret/README.md
> +- The project information is a JSON string with following schema:
After changing the input syntax this assumption should be updated

2023-06-26 08:43 UTC, javierbrea submitted a review, later dismissed

2023-06-27 12:22 UTC, javierbrea approved these changes

2023-06-27 12:29 UTC, rpiccio submitted a review, later dismissed

2023-06-28 06:56 UTC, javierbrea approved these changes

2023-06-28 06:57 UTC, merged