[WIP] refactor(CROSS-1455): move lib to shared module
Telefonica/cross-platform-actions pull request #61
Opened 2023-06-26 15:56 UTC by ismtabo

# [Jira issue ID] - [Title]

## Description

Moved write-secret lib logic to shared component.

## Check list

* [x] Unit tests have been executed locally
* [x] Build has been executed locally
* [x] The dist folder has been updated
* [ ] The documentation has been updated

2023-06-27 12:52 UTC, javierbrea requested changes

2023-06-27 12:52 UTC, javierbrea commented on components/github-actions-core/README.md
> +-->
The assumptions chapter is probably not needed. It was added to the other actions because they need some pre-requisites to work, such a repo name with x pattern, etc. But this, being a library, I suppose it won't require assumptions. Or at least they could be documented on each independent command in case there are.

2023-06-27 12:52 UTC, javierbrea commented on components/github-actions-core/README.md
> +## Inputs
Each command should have its own "params" or "API" subchapter, and examples. I would place API in first place, and then the example

```suggestion
#### Params
```

2023-06-27 12:52 UTC, javierbrea commented on components/github-actions-core/README.md
> +- List of created secrets with repository (and environment) information.
An example of the response would be useful, or a typed explanation as suggested in the params section

2023-06-27 12:52 UTC, javierbrea commented on components/github-actions-core/README.md
> +- `secret` - Name of the GitHub Secret to sync the secret to.
Detailed type of each param, as well as possible default values can be very useful.
```suggestion
- `secret`: _<string>_ - Name of the GitHub Secret to sync the secret to.
```

2023-06-27 12:52 UTC, javierbrea commented on write-secret/project.json
> +  "name": "write-secret",
I suppose this project now depends on the "github-actions-core" one, so, we should also add here the "build" dependency, or even better, to the root project.json file, something like:
```
build: [
 "^build"
]
```
It would probably also need to build before linting, because otherwise the eslint-plugin-import would fail, etc.

2023-06-27 12:52 UTC, javierbrea commented on components/github-actions-core/package.json
> +    "prepare": "cd ../../ && husky install"
Remove prepare script. Otherwise it would be repeated, because the main package.json file should be already doing it. If it is not doing it, please remove it from every package and add it only to the root.

2023-06-27 12:52 UTC, javierbrea commented on components/github-actions-core/README.md
> +
Would be a mention about the other exported object (logger types) be useful? Maybe we can add a "TypeScript" chapter mentioning exported types that are not so obvious that this package contains, such as the logger types.

2023-06-27 12:52 UTC, javierbrea commented on components/github-actions-core/src/commands/CreateSecrets.ts
> +export function createSecrets(
I suppose this method will be reused by other actions... and this is why it is being moved to the "github-actions-core" package, but, we should be careful about which methods do we move to a library with such a generic name. I mean, providing a package like "@aws-sdk/client-s3" may have sense from the point of view of distributing the whole library to clients, but building the whole library in a single package in the monorepo may produce a huge library that, when modified, it would affect to all other packages in the monorepo, so, any little change to the "core" would affect to all other elements. It is also true that this monorepo is "monoversion", so, every package will be always tested and released, but anyway we should try to organize packages in a more modular way.

The point here is: We should try to give more granular scopes to our reusable libraries, instead of creating a big "core" library affecting all other elements.

It's just a note to take into account for next PRs, and maybe we could even rethink the name of this library just now (I don't now which other methods are pending to be moved here, but maybe we can create two smaller libraries corresponding to more specific functional blocks instead of a generic one named "core")

2023-06-28 06:52 UTC, ismtabo commented
Wont do. Refactor is no required as there is no need to extract write-secret logic to shared component. See #60

2023-06-28 06:52 UTC, closed without merging